# Generated by Django 5.0.6 on 2024-05-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverification_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
