# Generated by Django 5.0.6 on 2024-05-23 03:21

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customusermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('accept_time', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('fee', models.IntegerField(default=1, validators=[utils.validators.IntegerRangeValidator(exclude=[], max=10, min=1)], verbose_name='Counsellor Fee')),
            ],
        ),
    ]
