# Generated by Django 5.0.6 on 2024-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_session_counsellor_id_session_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
    ]
