# Generated by Django 5.0.6 on 2024-05-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_setup_customusermodel_is_setup_and_more'),
    ]

    operations = [
    ]
