# Generated by Django 5.0.6 on 2024-05-30 07:40

from django.db import migrations
import json

def create_users(apps, schema_editor):
    with open('../data/userData.json', 'r') as file:
        _raw = file.read()

    data = json.loads(_raw)
    User = apps.get_model('accounts', 'CustomUserModel')

    for user in data:
        pass



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_setup_customusermodel_is_setup_and_more'),
    ]

    operations = [
    ]
