# Generated by Django 5.0.6 on 2024-05-23 03:21

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_session'),
        ('counsellor', '0002_counsellortype_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, null=True)),
                ('fee', models.IntegerField(default=1, validators=[utils.validators.IntegerRangeValidator(exclude=[], max=10, min=1)], verbose_name='Counsellor Fee')),
                ('sessions', models.ManyToManyField(related_name='related_to', through='accounts.Session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
