# Generated by Django 5.0.6 on 2024-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0003_counsellor'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellortype',
            name='counsellors',
            field=models.ManyToManyField(to='counsellor.counsellor'),
        ),
    ]
