# Generated by Django 5.0.6 on 2024-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1024),
        ),
    ]
