# Generated by Django 5.0.6 on 2024-05-26 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0009_alter_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1024)),
                ('preffered_date_from', models.DateField()),
                ('preffered_date_to', models.DateField()),
                ('preffered_time_from', models.TimeField()),
                ('preffered_time_to', models.TimeField()),
                ('cancelled', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counsellor.counsellor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
