# Generated by Django 5.0.6 on 2024-05-29 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0010_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellortype',
            name='counsellors',
            field=models.ManyToManyField(to='counsellor.counsellor'),
        ),
        migrations.AddField(
            model_name='counsellortype',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
