# Generated by Django 5.0.6 on 2024-05-30 13:46

from django.db import migrations
import json
from django.conf import settings
from accounts.models import CustomUserModel
from counsellor.models import CounsellorType
import math, random

def create_counsellors(apps, schema):
    return True
    print(settings.BASE_DIR)
    with open(settings.BASE_DIR / 'counsellor/data/counsellorData.json', 'r') as file:
        _raw = file.read()

    data = json.loads(_raw)
    # User = apps.get_model('accounts', 'CustomUserModel')
    User = CustomUserModel
    all_counsellors = CounsellorType.objects.all()

    for index, counsellor in enumerate(data):
        counsellor_obj = User.objects.create_counsellor(
            email=counsellor['email'],
            username=counsellor['name'],
            password='guest123'
        )

        counsellor_obj.user.image = 'static\\images\\users\\' + counsellor['image']
        counsellor_obj.introduction_section = counsellor['details']['introduction']
        counsellor_obj.qualification_section = counsellor['details']['qualifications']
        counsellor_obj.specialization_section = counsellor['details']['specialization']
        counsellor_obj.rates_section = counsellor['details']['rates']
        counsellor_obj.expected_fee = counsellor['fee']
        counsellor_obj.experience = counsellor['experience']

        types_id = []
        # for x in range(random.randint(1, 3)):
        #     break
        #     types_id.append(x)
        #     if x in types_id:
        #         continue

        #     counsellor_obj.counsellortype_set.add(all_counsellors[x])
        #     break

        counsellor_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0011_counsellortype_counsellors_counsellortype_users'),
    ]

    operations = [
        migrations.RunPython(create_counsellors)
    ]


