# Generated by Django 5.0.6 on 2024-05-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0012_auto_20240530_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
